var flights = [{cityFrom:'Barcelona',
cityTo: 'London',
price: '400',
duration: '2h'},
{cityFrom:'Madrid',
cityTo: 'London',
price: '100',
duration: '2.30h'},
{cityFrom:'Rome',
cityTo: 'Porto',
price: '300',
duration: '2h'},
{cityFrom:'Barcelona',
cityTo: 'Malaga',
price: '80',
duration: '2h'},
{cityFrom:'Barcelona',
cityTo: 'Prague',
price: '100',
duration: '2h'},
{cityFrom:'Milan',
cityTo: 'Barcelona',
price: '300',
duration: '2h'},]
