var flights = [{cityFrom:'Barcelona',
cityTo: 'London',
price: '200',
duration: '2h'},
{cityFrom:'Madrid',
cityTo: 'London',
price: '200',
duration: '2.30h'},
{cityFrom:'Rome',
cityTo: 'Porto',
price: '200',
duration: '2h'},
{cityFrom:'Malaga',
cityTo: 'Barcelona',
price: '200',
duration: '2h'},
{cityFrom:'Barcelona',
cityTo: 'Prague',
price: '200',
duration: '2h'},
{cityFrom:'Milan',
cityTo: 'Barcelona',
price: '200',
duration: '2h'},]
